### ISSUE TITLE
Errore inizializzazione progetto

### ISSUE THREAD

**Issue by salicius** [dcomedevelopers/provando-bootstrap-5#2]
Ciao, sono agli inizi e non so se ho fatto la serie di comandi giusta, ma mi da questo errore dal terminale (sono su macOS)

<img width="1280" alt="Screenshot 2021-02-04 at 23 15 49" src="https://user-images.githubusercontent.com/78569177/106962379-50bb8800-673f-11eb-8990-e6a5898fbfff.png">

**Comment by dcomedevelopers** [comment]
Ciao, potresti darmi la versione di npm che stai usando? Hai modificato qualcosa nel codice o hai solo scaricato la repo?

**Comment by salicius** [comment]
6.14.10, ho scaricato la repo, estratta e messa nel desktop

**Comment by dicrescenzoa** [comment]
Ho trovato un paio di problemi, cerco di capire che ha fatto ;) 

https://github.com/dcomedevelopers/provando-bootstrap-5/blob/main/package.json#L26

**Comment by dicrescenzoa** [comment]
@salicius ok ho risolto, appena posso faccio una modifica sulla repo. Per ora incolla e sostituisci questo nel package.json. Cancella un eventuale packagee-lock e rispara un npm install

```
{
  "name": "provando-bootstrap-5",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack --config ./webpack.config.js",
    "dev": "webpack serve --mode=development --config ./webpack.config.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/dcomedevelopers/provando-bootstrap-5.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/dcomedevelopers/provando-bootstrap-5/issues"
  },
  "homepage": "https://github.com/dcomedevelopers/provando-bootstrap-5#readme",
  "devDependencies": {
    "@popperjs/core": "^2.5.4",
    "autoprefixer": "^10.1.0",
    "bootstrap": "^5.0.0-beta1",
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^5.0.1",
    "html-webpack-plugin": "^5.0.0",
    "mini-css-extract-plugin": "^1.3.3",
    "postcss-loader": "^4.1.0",
    "sass": "^1.30.0",
    "sass-loader": "^10.1.0",
    "serve": "^11.3.2",
    "style-loader": "^2.0.0",
    "webpack": "^5.10.0",
    "webpack-cli": "^4.5.0",
    "webpack-dev-server": "^3.11.0"
  }
}
```

**Comment by salicius** [comment]
ok, ora funziona grazie mille, anche senza cancellare il json package-lock me lo ha fatto girare.
Ps, curisoità, perche vengono utilizzati questi mouli deprecati ?

<img width="573" alt="Screenshot 2021-02-05 at 15 55 55" src="https://user-images.githubusercontent.com/78569177/107050265-52cb2880-67cb-11eb-94c4-5a23badb50ac.png">

**Comment by dicrescenzoa** [comment]
Ottimo. Quelli sono warning per avvisare che qui moduli sono stati aggiornati. Se vedi il package.json noterai che non sono dipendenze "dirette", ma sono dipendenze delle dipendenze. Se siamo fortunati questi warning verranno risolti da chi mantiene quelle librerie, oppure possiamo fare qualcosa noi:

1. Aprire una PR su quei progetti proponendo l'aggiornamento del modulo
2. Creare un 'resolver' specifico nel nostro progetto per quella dipendenza con una versione piú aggiornata

**Comment by dcomedevelopers** [comment]
Issue risolta
